<?php 
/*
Plugin Name: Guegue Blocks
Plugin URI: https://www.guegue.com/
Description: Plugin de bloques personalizados para somosiberoamerica.org
Version: 1.0.0
Author: Omar Boza
Author URI: https://www.guegue.com/
Text Domain: gb
Generated By: http://ensuredomains.com
*/


if ( ! defined( 'WPINC' ) ) {die;} // end if

if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}